version: 0.2
phases:
  install:
    commands:
      - apt install unzip -y
      - wget https://releases.hashicorp.com/terraform/1.7.3/terraform_1.7.3_linux_amd64.zip
      - unzip terraform_1.7.3_linux_amd64.zip
      - mv terraform /usr/local/bin/
##pre-build
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform plan